### ISSUE TITLE
Unable to send photos!

### ISSUE THREAD

**Issue by seaside2** [unreal4u/telegram-api#68] opened 2017-09-26 09:23 UTC
Hello
I use this bot sdk and I found it very useful, but the problem that I faced is that I couldn't send most of photos with the help of "SendPhoto()"!
It seems that everything is OK except for the mentioned method.
I cannot send Images even as document!

This is the Exception message:

`Exception unreal4u\TelegramAPI\Exceptions\ClientException caught, message: An error occurred in the underlying stream`

Greetings

**Comment by unreal4u** [comment] 2017-09-26 09:39
If I'm not mistaken, that errors occurs when the file isn't readable: https://github.com/reactphp/http-client/blob/master/src/Response.php#L99-L103

So the next following question follows... what are your file permissions?

**Comment by seaside2** [comment] 2017-09-26 09:49
File permissions are 644.
I could send a PNG file with the same permission having a smaller size.

Thank you for quick respond.

**Comment by unreal4u** [comment] 2017-09-26 09:56
Oh that means that the issue might have to do with the filesize then :)

How much bytes is the file that gets sent successfully and how much bytes is the file that won't get sent?

Greetings.

**Comment by seaside2** [comment] 2017-09-26 10:40
I think situation is a little more complex! 
The file that I can't send is only 187 KB and the successfully sent file is very small: 4.86 KB.
"SendVideo()" method has the same problem, however CURL code snippet mentioned in the following link can successfully send these files.

[https://stackoverflow.com/questions/32296272/telegram-bot-api-how-to-send-a-photo-using-php](url)

I want to know how to solve this problem.

**Comment by unreal4u** [comment] 2017-09-26 10:59
Since we are working with a stream, I suspect it has something to do with the 8KiB limit, since it's the default of many internal processes, read http://php.net/manual/en/function.fread.php to understand a bit more about this logic.

This is clearly a bug, so with the info you've provided so far, I'll be able to test it, and hopefully fix it. 

Will do so tonight.

Greetings.

**Comment by unreal4u** [comment] 2017-09-26 20:35
I haven't been able to reproduce this on my local PC, so far I've been able to send images of a few MiB in size so far. The example files within this very same repo are actually bigger in size than 8KiB, so that shouldn't be the issue.

So there are definitively other factors at play. 

So a few more questions:
- Can you provide the images you're trying to send?
- What's the filename?
- Can you provide a code snippet to check if everything is ok there?
- What version of PHP are you using?
- What version of this library are you using?
- Are you able to run the example file (See `examples/send-photo.php`) correctly?

Greetings.

**Comment by seaside2** [comment] 2017-09-27 05:16
- I used sample images and some other images
- One of the filenames: photo_2017-09-26_11-56-14.jpg
- The current version of PHP in my host: 7.0
- I am using version 3.1.1 of your library by the help of composer:
`"require": {
    "unreal4u/telegram-api": "v3.1.1"
  }
`
- I have tested most of the sample files but the mention file (send-photo.php) is not working well.

**Comment by unreal4u** [comment] 2017-09-28 21:56
I haven't been able to reproduce the problem here, so it must be some setting or missing dependency or another thing.

Can you try to check what happens if you use the other available http client amp? Specifically, run the following example: https://github.com/unreal4u/telegram-api/blob/master/examples/send-photo-amp.php

If there is a problem, chances are that library will give us more insight into what's happening.

Greetings.

**Comment by unreal4u** [comment] 2017-09-28 21:58
Is there any chance you are using a CentOS box with SELinux enabled? If so, do you have something in your `/var/log/audit/audit.log` ?

**Comment by seaside2** [comment] 2017-09-29 06:19
After running send-photo-amp.php:

In my shared host:
> Exception Amp\Artax\DnsException caught, message: Resolving the specified domain failed: 'api.telegram.org'



In my VPS:
> Exception Amp\ByteStream\StreamException caught, message: Failed to write to socket Errno: 2; fwrite(): SSL operation failed with code 1. OpenSSL Error messages: error:1409F07F:SSL routines:SSL3_WRITE_PENDING:bad write retry

**Comment by unreal4u** [comment] 2017-10-02 11:18
It seems that you are not being able to resolve the domain.
Can you take a look at the documentation and use another DNS provider? (So don't use those from Google, they block anything they detect as being non-domestic)

https://github.com/reactphp/dns

I haven't been able to find anything based on the failed to write socket though, so maybe fix the DNS first.

Greetings.

**Comment by unreal4u** [comment] 2017-10-11 14:40
Closing this because no further questions were made. Should you still have problems, feel free to reopen this one or create a new issue.

Greetings.

**Closed by unreal4u** 2017-10-11 14:40 UTC
Labels: bug, cant-reproduce, question
